# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Mon Jul 26 15:09:58 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 648)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.tab)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.RateTrend = qwt.TauTrend(self.tab)
        self.RateTrend.setObjectName("RateTrend")
        self.hboxlayout1.addWidget(self.RateTrend)
        self.tauGroupBox_2 = widget.TauGroupBox(self.tab)
        self.tauGroupBox_2.setMinimumSize(QtCore.QSize(300, 400))
        self.tauGroupBox_2.setObjectName("tauGroupBox_2")
        self.gridlayout = QtGui.QGridLayout(self.tauGroupBox_2)
        self.gridlayout.setObjectName("gridlayout")
        self.label_18 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_18.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridlayout.addWidget(self.label_18, 0, 5, 1, 1)
        self.label_19 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_19.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridlayout.addWidget(self.label_19, 0, 6, 1, 1)
        self.label_5 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridlayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.avratebox = widget.TauValueLabel(self.tauGroupBox_2)
        self.avratebox.setObjectName("avratebox")
        self.gridlayout.addWidget(self.avratebox, 1, 1, 1, 3)
        self.label = QtGui.QLabel(self.tauGroupBox_2)
        self.label.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 1, 4, 1, 1)
        self.avrate_y1 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.avrate_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.avrate_y1.setObjectName("avrate_y1")
        self.gridlayout.addWidget(self.avrate_y1, 1, 5, 1, 1)
        self.avrate_y2 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.avrate_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.avrate_y2.setObjectName("avrate_y2")
        self.gridlayout.addWidget(self.avrate_y2, 1, 6, 1, 1)
        self.label_6 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridlayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.avthicknessbox = widget.TauValueLabel(self.tauGroupBox_2)
        self.avthicknessbox.setObjectName("avthicknessbox")
        self.gridlayout.addWidget(self.avthicknessbox, 2, 1, 1, 3)
        self.label_2 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_2.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 2, 4, 1, 1)
        self.avthickness_y1 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.avthickness_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.avthickness_y1.setObjectName("avthickness_y1")
        self.gridlayout.addWidget(self.avthickness_y1, 2, 5, 1, 1)
        self.avthickness_y2 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.avthickness_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.avthickness_y2.setObjectName("avthickness_y2")
        self.gridlayout.addWidget(self.avthickness_y2, 2, 6, 1, 1)
        self.label_7 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridlayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.rate1box = widget.TauValueLabel(self.tauGroupBox_2)
        self.rate1box.setObjectName("rate1box")
        self.gridlayout.addWidget(self.rate1box, 3, 1, 1, 3)
        self.label_4 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_4.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4, 3, 4, 1, 1)
        self.rate1_y1 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.rate1_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.rate1_y1.setObjectName("rate1_y1")
        self.gridlayout.addWidget(self.rate1_y1, 3, 5, 1, 1)
        self.rate1_y2 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.rate1_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.rate1_y2.setObjectName("rate1_y2")
        self.gridlayout.addWidget(self.rate1_y2, 3, 6, 1, 1)
        self.label_8 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridlayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.rate2box = widget.TauValueLabel(self.tauGroupBox_2)
        self.rate2box.setObjectName("rate2box")
        self.gridlayout.addWidget(self.rate2box, 4, 1, 1, 3)
        self.label_3 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_3.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridlayout.addWidget(self.label_3, 4, 4, 1, 1)
        self.rate2_y1 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.rate2_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.rate2_y1.setObjectName("rate2_y1")
        self.gridlayout.addWidget(self.rate2_y1, 4, 5, 1, 1)
        self.rate2_y2 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.rate2_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.rate2_y2.setObjectName("rate2_y2")
        self.gridlayout.addWidget(self.rate2_y2, 4, 6, 1, 1)
        self.label_9 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridlayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.thickness1box = widget.TauValueLabel(self.tauGroupBox_2)
        self.thickness1box.setObjectName("thickness1box")
        self.gridlayout.addWidget(self.thickness1box, 5, 1, 1, 3)
        self.label_11 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_11.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridlayout.addWidget(self.label_11, 5, 4, 1, 1)
        self.thickness1_y1 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.thickness1_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.thickness1_y1.setObjectName("thickness1_y1")
        self.gridlayout.addWidget(self.thickness1_y1, 5, 5, 1, 1)
        self.thickness1_y2 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.thickness1_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.thickness1_y2.setObjectName("thickness1_y2")
        self.gridlayout.addWidget(self.thickness1_y2, 5, 6, 1, 1)
        self.label_12 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridlayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.thickness2box = widget.TauValueLabel(self.tauGroupBox_2)
        self.thickness2box.setObjectName("thickness2box")
        self.gridlayout.addWidget(self.thickness2box, 6, 1, 1, 3)
        self.label_10 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_10.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridlayout.addWidget(self.label_10, 6, 4, 1, 1)
        self.thickness2_y1 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.thickness2_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.thickness2_y1.setObjectName("thickness2_y1")
        self.gridlayout.addWidget(self.thickness2_y1, 6, 5, 1, 1)
        self.thickness2_y2 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.thickness2_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.thickness2_y2.setObjectName("thickness2_y2")
        self.gridlayout.addWidget(self.thickness2_y2, 6, 6, 1, 1)
        self.label_14 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridlayout.addWidget(self.label_14, 7, 0, 1, 1)
        self.frequency1box = widget.TauValueLabel(self.tauGroupBox_2)
        self.frequency1box.setObjectName("frequency1box")
        self.gridlayout.addWidget(self.frequency1box, 7, 1, 1, 3)
        self.label_13 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_13.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridlayout.addWidget(self.label_13, 7, 4, 1, 1)
        self.frequency1_y1 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.frequency1_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.frequency1_y1.setObjectName("frequency1_y1")
        self.gridlayout.addWidget(self.frequency1_y1, 7, 5, 1, 1)
        self.frequency1_y2 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.frequency1_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.frequency1_y2.setObjectName("frequency1_y2")
        self.gridlayout.addWidget(self.frequency1_y2, 7, 6, 1, 1)
        self.label_15 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridlayout.addWidget(self.label_15, 8, 0, 1, 1)
        self.frequency2box = widget.TauValueLabel(self.tauGroupBox_2)
        self.frequency2box.setObjectName("frequency2box")
        self.gridlayout.addWidget(self.frequency2box, 8, 1, 1, 3)
        self.label_16 = QtGui.QLabel(self.tauGroupBox_2)
        self.label_16.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridlayout.addWidget(self.label_16, 8, 4, 1, 1)
        self.frequency2_y1 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.frequency2_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.frequency2_y1.setObjectName("frequency2_y1")
        self.gridlayout.addWidget(self.frequency2_y1, 8, 5, 1, 1)
        self.frequency2_y2 = QtGui.QCheckBox(self.tauGroupBox_2)
        self.frequency2_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.frequency2_y2.setObjectName("frequency2_y2")
        self.gridlayout.addWidget(self.frequency2_y2, 8, 6, 1, 1)
        self.startbutton1 = widget.TauCommandButton(self.tauGroupBox_2)
        self.startbutton1.setObjectName("startbutton1")
        self.gridlayout.addWidget(self.startbutton1, 9, 0, 1, 2)
        self.stopbutton1 = widget.TauCommandButton(self.tauGroupBox_2)
        self.stopbutton1.setEnabled(False)
        self.stopbutton1.setObjectName("stopbutton1")
        self.gridlayout.addWidget(self.stopbutton1, 9, 2, 1, 1)
        self.saveasbutton1 = widget.TauCommandButton(self.tauGroupBox_2)
        self.saveasbutton1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.saveasbutton1.setObjectName("saveasbutton1")
        self.gridlayout.addWidget(self.saveasbutton1, 9, 3, 1, 4)
        self.file1 = QtGui.QLabel(self.tauGroupBox_2)
        self.file1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.file1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.file1.setObjectName("file1")
        self.gridlayout.addWidget(self.file1, 10, 0, 1, 7)
        self.hboxlayout1.addWidget(self.tauGroupBox_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridlayout1 = QtGui.QGridLayout(self.tab_3)
        self.gridlayout1.setObjectName("gridlayout1")
        self.GaugeTrend = qwt.TauTrend(self.tab_3)
        self.GaugeTrend.setObjectName("GaugeTrend")
        self.gridlayout1.addWidget(self.GaugeTrend, 0, 0, 1, 1)
        self.tauGroupBox_3 = widget.TauGroupBox(self.tab_3)
        self.tauGroupBox_3.setMinimumSize(QtCore.QSize(300, 400))
        self.tauGroupBox_3.setObjectName("tauGroupBox_3")
        self.gridlayout2 = QtGui.QGridLayout(self.tauGroupBox_3)
        self.gridlayout2.setObjectName("gridlayout2")
        self.label_96 = QtGui.QLabel(self.tauGroupBox_3)
        self.label_96.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_96.setFont(font)
        self.label_96.setObjectName("label_96")
        self.gridlayout2.addWidget(self.label_96, 0, 5, 1, 1)
        self.label_97 = QtGui.QLabel(self.tauGroupBox_3)
        self.label_97.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_97.setFont(font)
        self.label_97.setObjectName("label_97")
        self.gridlayout2.addWidget(self.label_97, 0, 6, 1, 1)
        self.label_98 = QtGui.QLabel(self.tauGroupBox_3)
        self.label_98.setObjectName("label_98")
        self.gridlayout2.addWidget(self.label_98, 1, 0, 1, 1)
        self.pirani1box = widget.TauValueLabel(self.tauGroupBox_3)
        self.pirani1box.setObjectName("pirani1box")
        self.gridlayout2.addWidget(self.pirani1box, 1, 1, 1, 3)
        self.label_99 = QtGui.QLabel(self.tauGroupBox_3)
        self.label_99.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_99.setFont(font)
        self.label_99.setObjectName("label_99")
        self.gridlayout2.addWidget(self.label_99, 1, 4, 1, 1)
        self.pirani1_y1 = QtGui.QCheckBox(self.tauGroupBox_3)
        self.pirani1_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.pirani1_y1.setObjectName("pirani1_y1")
        self.gridlayout2.addWidget(self.pirani1_y1, 1, 5, 1, 1)
        self.pirani1_y2 = QtGui.QCheckBox(self.tauGroupBox_3)
        self.pirani1_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.pirani1_y2.setObjectName("pirani1_y2")
        self.gridlayout2.addWidget(self.pirani1_y2, 1, 6, 1, 1)
        self.label_100 = QtGui.QLabel(self.tauGroupBox_3)
        self.label_100.setObjectName("label_100")
        self.gridlayout2.addWidget(self.label_100, 2, 0, 1, 1)
        self.pirani2box = widget.TauValueLabel(self.tauGroupBox_3)
        self.pirani2box.setObjectName("pirani2box")
        self.gridlayout2.addWidget(self.pirani2box, 2, 1, 1, 3)
        self.label_101 = QtGui.QLabel(self.tauGroupBox_3)
        self.label_101.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_101.setFont(font)
        self.label_101.setObjectName("label_101")
        self.gridlayout2.addWidget(self.label_101, 2, 4, 1, 1)
        self.pirani2_y1 = QtGui.QCheckBox(self.tauGroupBox_3)
        self.pirani2_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.pirani2_y1.setObjectName("pirani2_y1")
        self.gridlayout2.addWidget(self.pirani2_y1, 2, 5, 1, 1)
        self.pirani2_y2 = QtGui.QCheckBox(self.tauGroupBox_3)
        self.pirani2_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.pirani2_y2.setObjectName("pirani2_y2")
        self.gridlayout2.addWidget(self.pirani2_y2, 2, 6, 1, 1)
        self.label_102 = QtGui.QLabel(self.tauGroupBox_3)
        self.label_102.setObjectName("label_102")
        self.gridlayout2.addWidget(self.label_102, 3, 0, 1, 1)
        self.penning1box = widget.TauValueLabel(self.tauGroupBox_3)
        self.penning1box.setObjectName("penning1box")
        self.gridlayout2.addWidget(self.penning1box, 3, 1, 1, 3)
        self.label_103 = QtGui.QLabel(self.tauGroupBox_3)
        self.label_103.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_103.setFont(font)
        self.label_103.setObjectName("label_103")
        self.gridlayout2.addWidget(self.label_103, 3, 4, 1, 1)
        self.penning1_y1 = QtGui.QCheckBox(self.tauGroupBox_3)
        self.penning1_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.penning1_y1.setObjectName("penning1_y1")
        self.gridlayout2.addWidget(self.penning1_y1, 3, 5, 1, 1)
        self.penning1_y2 = QtGui.QCheckBox(self.tauGroupBox_3)
        self.penning1_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.penning1_y2.setObjectName("penning1_y2")
        self.gridlayout2.addWidget(self.penning1_y2, 3, 6, 1, 1)
        self.label_104 = QtGui.QLabel(self.tauGroupBox_3)
        self.label_104.setObjectName("label_104")
        self.gridlayout2.addWidget(self.label_104, 4, 0, 1, 1)
        self.penning2box = widget.TauValueLabel(self.tauGroupBox_3)
        self.penning2box.setObjectName("penning2box")
        self.gridlayout2.addWidget(self.penning2box, 4, 1, 1, 3)
        self.label_105 = QtGui.QLabel(self.tauGroupBox_3)
        self.label_105.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_105.setFont(font)
        self.label_105.setObjectName("label_105")
        self.gridlayout2.addWidget(self.label_105, 4, 4, 1, 1)
        self.penning2_y1 = QtGui.QCheckBox(self.tauGroupBox_3)
        self.penning2_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.penning2_y1.setObjectName("penning2_y1")
        self.gridlayout2.addWidget(self.penning2_y1, 4, 5, 1, 1)
        self.penning2_y2 = QtGui.QCheckBox(self.tauGroupBox_3)
        self.penning2_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.penning2_y2.setObjectName("penning2_y2")
        self.gridlayout2.addWidget(self.penning2_y2, 4, 6, 1, 1)
        self.startbutton2 = widget.TauCommandButton(self.tauGroupBox_3)
        self.startbutton2.setObjectName("startbutton2")
        self.gridlayout2.addWidget(self.startbutton2, 9, 0, 1, 2)
        self.stopbutton2 = widget.TauCommandButton(self.tauGroupBox_3)
        self.stopbutton2.setEnabled(False)
        self.stopbutton2.setObjectName("stopbutton2")
        self.gridlayout2.addWidget(self.stopbutton2, 9, 2, 1, 1)
        self.saveasbutton2 = widget.TauCommandButton(self.tauGroupBox_3)
        self.saveasbutton2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.saveasbutton2.setObjectName("saveasbutton2")
        self.gridlayout2.addWidget(self.saveasbutton2, 9, 3, 1, 4)
        self.file2 = QtGui.QLabel(self.tauGroupBox_3)
        self.file2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.file2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.file2.setObjectName("file2")
        self.gridlayout2.addWidget(self.file2, 10, 0, 1, 7)
        self.gridlayout1.addWidget(self.tauGroupBox_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridlayout3 = QtGui.QGridLayout(self.tab_2)
        self.gridlayout3.setObjectName("gridlayout3")
        self.RateTrend_5 = qwt.TauTrend(self.tab_2)
        self.RateTrend_5.setObjectName("RateTrend_5")
        self.gridlayout3.addWidget(self.RateTrend_5, 0, 0, 1, 1)
        self.tauGroupBox_6 = widget.TauGroupBox(self.tab_2)
        self.tauGroupBox_6.setMinimumSize(QtCore.QSize(300, 400))
        self.tauGroupBox_6.setObjectName("tauGroupBox_6")
        self.gridlayout4 = QtGui.QGridLayout(self.tauGroupBox_6)
        self.gridlayout4.setObjectName("gridlayout4")
        self.label_115 = QtGui.QLabel(self.tauGroupBox_6)
        self.label_115.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_115.setFont(font)
        self.label_115.setObjectName("label_115")
        self.gridlayout4.addWidget(self.label_115, 0, 5, 1, 1)
        self.label_116 = QtGui.QLabel(self.tauGroupBox_6)
        self.label_116.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_116.setFont(font)
        self.label_116.setObjectName("label_116")
        self.gridlayout4.addWidget(self.label_116, 0, 6, 1, 1)
        self.label_117 = QtGui.QLabel(self.tauGroupBox_6)
        self.label_117.setObjectName("label_117")
        self.gridlayout4.addWidget(self.label_117, 1, 0, 1, 1)
        self.capacitor1box = widget.TauValueLabel(self.tauGroupBox_6)
        self.capacitor1box.setObjectName("capacitor1box")
        self.gridlayout4.addWidget(self.capacitor1box, 1, 1, 1, 3)
        self.label_118 = QtGui.QLabel(self.tauGroupBox_6)
        self.label_118.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_118.setFont(font)
        self.label_118.setObjectName("label_118")
        self.gridlayout4.addWidget(self.label_118, 1, 4, 1, 1)
        self.capacitor1_y1 = QtGui.QCheckBox(self.tauGroupBox_6)
        self.capacitor1_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.capacitor1_y1.setObjectName("capacitor1_y1")
        self.gridlayout4.addWidget(self.capacitor1_y1, 1, 5, 1, 1)
        self.capacitor1_y2 = QtGui.QCheckBox(self.tauGroupBox_6)
        self.capacitor1_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.capacitor1_y2.setObjectName("capacitor1_y2")
        self.gridlayout4.addWidget(self.capacitor1_y2, 1, 6, 1, 1)
        self.label_119 = QtGui.QLabel(self.tauGroupBox_6)
        self.label_119.setObjectName("label_119")
        self.gridlayout4.addWidget(self.label_119, 2, 0, 1, 1)
        self.capacitor2box = widget.TauValueLabel(self.tauGroupBox_6)
        self.capacitor2box.setObjectName("capacitor2box")
        self.gridlayout4.addWidget(self.capacitor2box, 2, 1, 1, 3)
        self.label_120 = QtGui.QLabel(self.tauGroupBox_6)
        self.label_120.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_120.setFont(font)
        self.label_120.setObjectName("label_120")
        self.gridlayout4.addWidget(self.label_120, 2, 4, 1, 1)
        self.capacitor2_y1 = QtGui.QCheckBox(self.tauGroupBox_6)
        self.capacitor2_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.capacitor2_y1.setObjectName("capacitor2_y1")
        self.gridlayout4.addWidget(self.capacitor2_y1, 2, 5, 1, 1)
        self.capacitor2_y2 = QtGui.QCheckBox(self.tauGroupBox_6)
        self.capacitor2_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.capacitor2_y2.setObjectName("capacitor2_y2")
        self.gridlayout4.addWidget(self.capacitor2_y2, 2, 6, 1, 1)
        self.label_121 = QtGui.QLabel(self.tauGroupBox_6)
        self.label_121.setObjectName("label_121")
        self.gridlayout4.addWidget(self.label_121, 3, 0, 1, 1)
        self.dcbiasbox = widget.TauValueLabel(self.tauGroupBox_6)
        self.dcbiasbox.setObjectName("dcbiasbox")
        self.gridlayout4.addWidget(self.dcbiasbox, 3, 1, 1, 3)
        self.label_122 = QtGui.QLabel(self.tauGroupBox_6)
        self.label_122.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_122.setFont(font)
        self.label_122.setObjectName("label_122")
        self.gridlayout4.addWidget(self.label_122, 3, 4, 1, 1)
        self.dcbias_y1 = QtGui.QCheckBox(self.tauGroupBox_6)
        self.dcbias_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.dcbias_y1.setObjectName("dcbias_y1")
        self.gridlayout4.addWidget(self.dcbias_y1, 3, 5, 1, 1)
        self.dcbias_y2 = QtGui.QCheckBox(self.tauGroupBox_6)
        self.dcbias_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.dcbias_y2.setObjectName("dcbias_y2")
        self.gridlayout4.addWidget(self.dcbias_y2, 3, 6, 1, 1)
        self.startbutton3 = widget.TauCommandButton(self.tauGroupBox_6)
        self.startbutton3.setObjectName("startbutton3")
        self.gridlayout4.addWidget(self.startbutton3, 9, 0, 1, 2)
        self.stopbutton3 = widget.TauCommandButton(self.tauGroupBox_6)
        self.stopbutton3.setEnabled(False)
        self.stopbutton3.setObjectName("stopbutton3")
        self.gridlayout4.addWidget(self.stopbutton3, 9, 2, 1, 1)
        self.saveasbutton3 = widget.TauCommandButton(self.tauGroupBox_6)
        self.saveasbutton3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.saveasbutton3.setObjectName("saveasbutton3")
        self.gridlayout4.addWidget(self.saveasbutton3, 9, 3, 1, 4)
        self.file3 = QtGui.QLabel(self.tauGroupBox_6)
        self.file3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.file3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.file3.setObjectName("file3")
        self.gridlayout4.addWidget(self.file3, 10, 0, 1, 7)
        self.gridlayout3.addWidget(self.tauGroupBox_6, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridlayout5 = QtGui.QGridLayout(self.tab_4)
        self.gridlayout5.setObjectName("gridlayout5")
        self.RateTrend_6 = qwt.TauTrend(self.tab_4)
        self.RateTrend_6.setObjectName("RateTrend_6")
        self.gridlayout5.addWidget(self.RateTrend_6, 0, 0, 1, 1)
        self.tauGroupBox_7 = widget.TauGroupBox(self.tab_4)
        self.tauGroupBox_7.setMinimumSize(QtCore.QSize(300, 400))
        self.tauGroupBox_7.setObjectName("tauGroupBox_7")
        self.gridlayout6 = QtGui.QGridLayout(self.tauGroupBox_7)
        self.gridlayout6.setObjectName("gridlayout6")
        self.label_134 = QtGui.QLabel(self.tauGroupBox_7)
        self.label_134.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_134.setFont(font)
        self.label_134.setObjectName("label_134")
        self.gridlayout6.addWidget(self.label_134, 0, 5, 1, 1)
        self.label_135 = QtGui.QLabel(self.tauGroupBox_7)
        self.label_135.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_135.setFont(font)
        self.label_135.setObjectName("label_135")
        self.gridlayout6.addWidget(self.label_135, 0, 6, 1, 1)
        self.label_136 = QtGui.QLabel(self.tauGroupBox_7)
        self.label_136.setObjectName("label_136")
        self.gridlayout6.addWidget(self.label_136, 1, 0, 1, 1)
        self.setpointbox = widget.TauValueLabel(self.tauGroupBox_7)
        self.setpointbox.setObjectName("setpointbox")
        self.gridlayout6.addWidget(self.setpointbox, 1, 1, 1, 3)
        self.label_137 = QtGui.QLabel(self.tauGroupBox_7)
        self.label_137.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_137.setFont(font)
        self.label_137.setObjectName("label_137")
        self.gridlayout6.addWidget(self.label_137, 1, 4, 1, 1)
        self.setpoint_y1 = QtGui.QCheckBox(self.tauGroupBox_7)
        self.setpoint_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.setpoint_y1.setObjectName("setpoint_y1")
        self.gridlayout6.addWidget(self.setpoint_y1, 1, 5, 1, 1)
        self.setpoint_y2 = QtGui.QCheckBox(self.tauGroupBox_7)
        self.setpoint_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.setpoint_y2.setObjectName("setpoint_y2")
        self.gridlayout6.addWidget(self.setpoint_y2, 1, 6, 1, 1)
        self.label_138 = QtGui.QLabel(self.tauGroupBox_7)
        self.label_138.setObjectName("label_138")
        self.gridlayout6.addWidget(self.label_138, 2, 0, 1, 1)
        self.forwardbox = widget.TauValueLabel(self.tauGroupBox_7)
        self.forwardbox.setObjectName("forwardbox")
        self.gridlayout6.addWidget(self.forwardbox, 2, 1, 1, 3)
        self.label_139 = QtGui.QLabel(self.tauGroupBox_7)
        self.label_139.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_139.setFont(font)
        self.label_139.setObjectName("label_139")
        self.gridlayout6.addWidget(self.label_139, 2, 4, 1, 1)
        self.forward_y1 = QtGui.QCheckBox(self.tauGroupBox_7)
        self.forward_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.forward_y1.setObjectName("forward_y1")
        self.gridlayout6.addWidget(self.forward_y1, 2, 5, 1, 1)
        self.forward_y2 = QtGui.QCheckBox(self.tauGroupBox_7)
        self.forward_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.forward_y2.setObjectName("forward_y2")
        self.gridlayout6.addWidget(self.forward_y2, 2, 6, 1, 1)
        self.label_140 = QtGui.QLabel(self.tauGroupBox_7)
        self.label_140.setObjectName("label_140")
        self.gridlayout6.addWidget(self.label_140, 3, 0, 1, 1)
        self.reflectedbox = widget.TauValueLabel(self.tauGroupBox_7)
        self.reflectedbox.setObjectName("reflectedbox")
        self.gridlayout6.addWidget(self.reflectedbox, 3, 1, 1, 3)
        self.label_141 = QtGui.QLabel(self.tauGroupBox_7)
        self.label_141.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_141.setFont(font)
        self.label_141.setObjectName("label_141")
        self.gridlayout6.addWidget(self.label_141, 3, 4, 1, 1)
        self.reflected_y1 = QtGui.QCheckBox(self.tauGroupBox_7)
        self.reflected_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.reflected_y1.setObjectName("reflected_y1")
        self.gridlayout6.addWidget(self.reflected_y1, 3, 5, 1, 1)
        self.reflected_y2 = QtGui.QCheckBox(self.tauGroupBox_7)
        self.reflected_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.reflected_y2.setObjectName("reflected_y2")
        self.gridlayout6.addWidget(self.reflected_y2, 3, 6, 1, 1)
        self.label_142 = QtGui.QLabel(self.tauGroupBox_7)
        self.label_142.setObjectName("label_142")
        self.gridlayout6.addWidget(self.label_142, 4, 0, 1, 1)
        self.loadbox = widget.TauValueLabel(self.tauGroupBox_7)
        self.loadbox.setObjectName("loadbox")
        self.gridlayout6.addWidget(self.loadbox, 4, 1, 1, 3)
        self.label_143 = QtGui.QLabel(self.tauGroupBox_7)
        self.label_143.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_143.setFont(font)
        self.label_143.setObjectName("label_143")
        self.gridlayout6.addWidget(self.label_143, 4, 4, 1, 1)
        self.load_y1 = QtGui.QCheckBox(self.tauGroupBox_7)
        self.load_y1.setMaximumSize(QtCore.QSize(16, 16))
        self.load_y1.setObjectName("load_y1")
        self.gridlayout6.addWidget(self.load_y1, 4, 5, 1, 1)
        self.load_y2 = QtGui.QCheckBox(self.tauGroupBox_7)
        self.load_y2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.load_y2.setObjectName("load_y2")
        self.gridlayout6.addWidget(self.load_y2, 4, 6, 1, 1)
        self.startbutton4 = widget.TauCommandButton(self.tauGroupBox_7)
        self.startbutton4.setObjectName("startbutton4")
        self.gridlayout6.addWidget(self.startbutton4, 9, 0, 1, 2)
        self.stopbutton4 = widget.TauCommandButton(self.tauGroupBox_7)
        self.stopbutton4.setEnabled(False)
        self.stopbutton4.setObjectName("stopbutton4")
        self.gridlayout6.addWidget(self.stopbutton4, 9, 2, 1, 1)
        self.saveasbutton4 = widget.TauCommandButton(self.tauGroupBox_7)
        self.saveasbutton4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.saveasbutton4.setObjectName("saveasbutton4")
        self.gridlayout6.addWidget(self.saveasbutton4, 9, 3, 1, 4)
        self.file4 = QtGui.QLabel(self.tauGroupBox_7)
        self.file4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.file4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.file4.setObjectName("file4")
        self.gridlayout6.addWidget(self.file4, 10, 0, 1, 7)
        self.gridlayout5.addWidget(self.tauGroupBox_7, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.gridlayout7 = QtGui.QGridLayout(self.tab_13)
        self.gridlayout7.setObjectName("gridlayout7")
        self.RateTrend_4 = qwt.TauTrend(self.tab_13)
        self.RateTrend_4.setObjectName("RateTrend_4")
        self.gridlayout7.addWidget(self.RateTrend_4, 0, 0, 1, 1)
        self.tauGroupBox_8 = widget.TauGroupBox(self.tab_13)
        self.tauGroupBox_8.setMinimumSize(QtCore.QSize(300, 400))
        self.tauGroupBox_8.setObjectName("tauGroupBox_8")
        self.gridlayout8 = QtGui.QGridLayout(self.tauGroupBox_8)
        self.gridlayout8.setMargin(0)
        self.gridlayout8.setVerticalSpacing(0)
        self.gridlayout8.setObjectName("gridlayout8")
        self.label_106 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_106.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_106.setFont(font)
        self.label_106.setObjectName("label_106")
        self.gridlayout8.addWidget(self.label_106, 0, 8, 1, 1)
        self.label_107 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_107.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_107.setFont(font)
        self.label_107.setObjectName("label_107")
        self.gridlayout8.addWidget(self.label_107, 0, 9, 1, 1)
        self.label_17 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_17.setObjectName("label_17")
        self.gridlayout8.addWidget(self.label_17, 1, 0, 1, 1)
        self.avratebox_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.avratebox_2.setObjectName("avratebox_2")
        self.gridlayout8.addWidget(self.avratebox_2, 1, 1, 1, 6)
        self.label_108 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_108.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_108.setFont(font)
        self.label_108.setObjectName("label_108")
        self.gridlayout8.addWidget(self.label_108, 1, 7, 1, 1)
        self.avrate_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.avrate_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.avrate_y1_2.setObjectName("avrate_y1_2")
        self.gridlayout8.addWidget(self.avrate_y1_2, 1, 8, 1, 1)
        self.avrate_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.avrate_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.avrate_y2_2.setObjectName("avrate_y2_2")
        self.gridlayout8.addWidget(self.avrate_y2_2, 1, 9, 1, 1)
        self.label_109 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_109.setObjectName("label_109")
        self.gridlayout8.addWidget(self.label_109, 2, 0, 1, 1)
        self.avthicknessbox_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.avthicknessbox_2.setObjectName("avthicknessbox_2")
        self.gridlayout8.addWidget(self.avthicknessbox_2, 2, 1, 1, 6)
        self.label_110 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_110.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_110.setFont(font)
        self.label_110.setObjectName("label_110")
        self.gridlayout8.addWidget(self.label_110, 2, 7, 1, 1)
        self.avthickness_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.avthickness_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.avthickness_y1_2.setObjectName("avthickness_y1_2")
        self.gridlayout8.addWidget(self.avthickness_y1_2, 2, 8, 1, 1)
        self.avthickness_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.avthickness_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.avthickness_y2_2.setObjectName("avthickness_y2_2")
        self.gridlayout8.addWidget(self.avthickness_y2_2, 2, 9, 1, 1)
        self.label_111 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_111.setObjectName("label_111")
        self.gridlayout8.addWidget(self.label_111, 3, 0, 1, 1)
        self.rate1box_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.rate1box_2.setObjectName("rate1box_2")
        self.gridlayout8.addWidget(self.rate1box_2, 3, 1, 1, 6)
        self.label_112 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_112.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_112.setFont(font)
        self.label_112.setObjectName("label_112")
        self.gridlayout8.addWidget(self.label_112, 3, 7, 1, 1)
        self.rate1_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.rate1_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.rate1_y1_2.setObjectName("rate1_y1_2")
        self.gridlayout8.addWidget(self.rate1_y1_2, 3, 8, 1, 1)
        self.rate1_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.rate1_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.rate1_y2_2.setObjectName("rate1_y2_2")
        self.gridlayout8.addWidget(self.rate1_y2_2, 3, 9, 1, 1)
        self.label_113 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_113.setObjectName("label_113")
        self.gridlayout8.addWidget(self.label_113, 4, 0, 1, 1)
        self.rate2box_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.rate2box_2.setObjectName("rate2box_2")
        self.gridlayout8.addWidget(self.rate2box_2, 4, 1, 1, 6)
        self.label_114 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_114.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_114.setFont(font)
        self.label_114.setObjectName("label_114")
        self.gridlayout8.addWidget(self.label_114, 4, 7, 1, 1)
        self.rate2_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.rate2_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.rate2_y1_2.setObjectName("rate2_y1_2")
        self.gridlayout8.addWidget(self.rate2_y1_2, 4, 8, 1, 1)
        self.rate2_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.rate2_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.rate2_y2_2.setObjectName("rate2_y2_2")
        self.gridlayout8.addWidget(self.rate2_y2_2, 4, 9, 1, 1)
        self.label_123 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_123.setObjectName("label_123")
        self.gridlayout8.addWidget(self.label_123, 5, 0, 1, 1)
        self.thickness1box_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.thickness1box_2.setObjectName("thickness1box_2")
        self.gridlayout8.addWidget(self.thickness1box_2, 5, 1, 1, 6)
        self.label_124 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_124.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_124.setFont(font)
        self.label_124.setObjectName("label_124")
        self.gridlayout8.addWidget(self.label_124, 5, 7, 1, 1)
        self.thickness1_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.thickness1_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.thickness1_y1_2.setObjectName("thickness1_y1_2")
        self.gridlayout8.addWidget(self.thickness1_y1_2, 5, 8, 1, 1)
        self.thickness1_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.thickness1_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.thickness1_y2_2.setObjectName("thickness1_y2_2")
        self.gridlayout8.addWidget(self.thickness1_y2_2, 5, 9, 1, 1)
        self.label_125 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_125.setObjectName("label_125")
        self.gridlayout8.addWidget(self.label_125, 6, 0, 1, 1)
        self.thickness2box_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.thickness2box_2.setObjectName("thickness2box_2")
        self.gridlayout8.addWidget(self.thickness2box_2, 6, 1, 1, 6)
        self.label_126 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_126.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_126.setFont(font)
        self.label_126.setObjectName("label_126")
        self.gridlayout8.addWidget(self.label_126, 6, 7, 1, 1)
        self.thickness2_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.thickness2_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.thickness2_y1_2.setObjectName("thickness2_y1_2")
        self.gridlayout8.addWidget(self.thickness2_y1_2, 6, 8, 1, 1)
        self.thickness2_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.thickness2_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.thickness2_y2_2.setObjectName("thickness2_y2_2")
        self.gridlayout8.addWidget(self.thickness2_y2_2, 6, 9, 1, 1)
        self.label_127 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_127.setObjectName("label_127")
        self.gridlayout8.addWidget(self.label_127, 7, 0, 1, 1)
        self.frequency1box_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.frequency1box_2.setObjectName("frequency1box_2")
        self.gridlayout8.addWidget(self.frequency1box_2, 7, 1, 1, 6)
        self.label_128 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_128.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_128.setFont(font)
        self.label_128.setObjectName("label_128")
        self.gridlayout8.addWidget(self.label_128, 7, 7, 1, 1)
        self.frequency1_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.frequency1_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.frequency1_y1_2.setObjectName("frequency1_y1_2")
        self.gridlayout8.addWidget(self.frequency1_y1_2, 7, 8, 1, 1)
        self.frequency1_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.frequency1_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.frequency1_y2_2.setObjectName("frequency1_y2_2")
        self.gridlayout8.addWidget(self.frequency1_y2_2, 7, 9, 1, 1)
        self.label_129 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_129.setObjectName("label_129")
        self.gridlayout8.addWidget(self.label_129, 8, 0, 1, 1)
        self.frequency2box_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.frequency2box_2.setObjectName("frequency2box_2")
        self.gridlayout8.addWidget(self.frequency2box_2, 8, 1, 1, 6)
        self.label_130 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_130.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_130.setFont(font)
        self.label_130.setObjectName("label_130")
        self.gridlayout8.addWidget(self.label_130, 8, 7, 1, 1)
        self.frequency2_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.frequency2_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.frequency2_y1_2.setObjectName("frequency2_y1_2")
        self.gridlayout8.addWidget(self.frequency2_y1_2, 8, 8, 1, 1)
        self.frequency2_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.frequency2_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.frequency2_y2_2.setObjectName("frequency2_y2_2")
        self.gridlayout8.addWidget(self.frequency2_y2_2, 8, 9, 1, 1)
        self.label_131 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_131.setObjectName("label_131")
        self.gridlayout8.addWidget(self.label_131, 9, 0, 1, 4)
        self.pirani1box_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.pirani1box_2.setObjectName("pirani1box_2")
        self.gridlayout8.addWidget(self.pirani1box_2, 9, 4, 1, 3)
        self.label_146 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_146.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_146.setFont(font)
        self.label_146.setObjectName("label_146")
        self.gridlayout8.addWidget(self.label_146, 9, 7, 1, 1)
        self.pirani1_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.pirani1_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.pirani1_y1_2.setObjectName("pirani1_y1_2")
        self.gridlayout8.addWidget(self.pirani1_y1_2, 9, 8, 1, 1)
        self.pirani1_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.pirani1_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.pirani1_y2_2.setObjectName("pirani1_y2_2")
        self.gridlayout8.addWidget(self.pirani1_y2_2, 9, 9, 1, 1)
        self.label_147 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_147.setObjectName("label_147")
        self.gridlayout8.addWidget(self.label_147, 10, 0, 1, 4)
        self.pirani2box_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.pirani2box_2.setObjectName("pirani2box_2")
        self.gridlayout8.addWidget(self.pirani2box_2, 10, 4, 1, 3)
        self.label_149 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_149.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_149.setFont(font)
        self.label_149.setObjectName("label_149")
        self.gridlayout8.addWidget(self.label_149, 10, 7, 1, 1)
        self.pirani2_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.pirani2_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.pirani2_y1_2.setObjectName("pirani2_y1_2")
        self.gridlayout8.addWidget(self.pirani2_y1_2, 10, 8, 1, 1)
        self.pirani2_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.pirani2_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.pirani2_y2_2.setObjectName("pirani2_y2_2")
        self.gridlayout8.addWidget(self.pirani2_y2_2, 10, 9, 1, 1)
        self.label_148 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_148.setObjectName("label_148")
        self.gridlayout8.addWidget(self.label_148, 11, 0, 1, 4)
        self.penning1box_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.penning1box_2.setObjectName("penning1box_2")
        self.gridlayout8.addWidget(self.penning1box_2, 11, 4, 1, 3)
        self.label_145 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_145.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_145.setFont(font)
        self.label_145.setObjectName("label_145")
        self.gridlayout8.addWidget(self.label_145, 11, 7, 1, 1)
        self.penning1_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.penning1_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.penning1_y1_2.setObjectName("penning1_y1_2")
        self.gridlayout8.addWidget(self.penning1_y1_2, 11, 8, 1, 1)
        self.penning1_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.penning1_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.penning1_y2_2.setObjectName("penning1_y2_2")
        self.gridlayout8.addWidget(self.penning1_y2_2, 11, 9, 1, 1)
        self.label_132 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_132.setObjectName("label_132")
        self.gridlayout8.addWidget(self.label_132, 12, 0, 1, 4)
        self.penning2box_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.penning2box_2.setObjectName("penning2box_2")
        self.gridlayout8.addWidget(self.penning2box_2, 12, 4, 1, 3)
        self.label_144 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_144.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_144.setFont(font)
        self.label_144.setObjectName("label_144")
        self.gridlayout8.addWidget(self.label_144, 12, 7, 1, 1)
        self.penning2_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.penning2_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.penning2_y1_2.setObjectName("penning2_y1_2")
        self.gridlayout8.addWidget(self.penning2_y1_2, 12, 8, 1, 1)
        self.penning2_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.penning2_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.penning2_y2_2.setObjectName("penning2_y2_2")
        self.gridlayout8.addWidget(self.penning2_y2_2, 12, 9, 1, 1)
        self.label_150 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_150.setObjectName("label_150")
        self.gridlayout8.addWidget(self.label_150, 13, 0, 1, 3)
        self.capacitor1box_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.capacitor1box_2.setObjectName("capacitor1box_2")
        self.gridlayout8.addWidget(self.capacitor1box_2, 13, 3, 1, 4)
        self.label_151 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_151.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_151.setFont(font)
        self.label_151.setObjectName("label_151")
        self.gridlayout8.addWidget(self.label_151, 13, 7, 1, 1)
        self.capacitor1_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.capacitor1_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.capacitor1_y1_2.setObjectName("capacitor1_y1_2")
        self.gridlayout8.addWidget(self.capacitor1_y1_2, 13, 8, 1, 1)
        self.capacitor1_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.capacitor1_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.capacitor1_y2_2.setObjectName("capacitor1_y2_2")
        self.gridlayout8.addWidget(self.capacitor1_y2_2, 13, 9, 1, 1)
        self.label_153 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_153.setObjectName("label_153")
        self.gridlayout8.addWidget(self.label_153, 14, 0, 1, 3)
        self.capacitor2box_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.capacitor2box_2.setObjectName("capacitor2box_2")
        self.gridlayout8.addWidget(self.capacitor2box_2, 14, 3, 1, 4)
        self.label_155 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_155.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_155.setFont(font)
        self.label_155.setObjectName("label_155")
        self.gridlayout8.addWidget(self.label_155, 14, 7, 1, 1)
        self.capacitor2_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.capacitor2_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.capacitor2_y1_2.setObjectName("capacitor2_y1_2")
        self.gridlayout8.addWidget(self.capacitor2_y1_2, 14, 8, 1, 1)
        self.capacitor2_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.capacitor2_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.capacitor2_y2_2.setObjectName("capacitor2_y2_2")
        self.gridlayout8.addWidget(self.capacitor2_y2_2, 14, 9, 1, 1)
        self.label_156 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_156.setObjectName("label_156")
        self.gridlayout8.addWidget(self.label_156, 15, 0, 1, 3)
        self.dcbiasbox_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.dcbiasbox_2.setObjectName("dcbiasbox_2")
        self.gridlayout8.addWidget(self.dcbiasbox_2, 15, 3, 1, 4)
        self.label_154 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_154.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_154.setFont(font)
        self.label_154.setObjectName("label_154")
        self.gridlayout8.addWidget(self.label_154, 15, 7, 1, 1)
        self.dcbias_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.dcbias_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.dcbias_y1_2.setObjectName("dcbias_y1_2")
        self.gridlayout8.addWidget(self.dcbias_y1_2, 15, 8, 1, 1)
        self.dcbias_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.dcbias_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.dcbias_y2_2.setObjectName("dcbias_y2_2")
        self.gridlayout8.addWidget(self.dcbias_y2_2, 15, 9, 1, 1)
        self.label_158 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_158.setObjectName("label_158")
        self.gridlayout8.addWidget(self.label_158, 16, 0, 1, 2)
        self.setpointbox_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.setpointbox_2.setObjectName("setpointbox_2")
        self.gridlayout8.addWidget(self.setpointbox_2, 16, 2, 1, 4)
        self.label_164 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_164.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_164.setFont(font)
        self.label_164.setObjectName("label_164")
        self.gridlayout8.addWidget(self.label_164, 16, 6, 1, 1)
        self.setpoint_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.setpoint_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.setpoint_y1_2.setObjectName("setpoint_y1_2")
        self.gridlayout8.addWidget(self.setpoint_y1_2, 16, 7, 1, 1)
        self.setpoint_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.setpoint_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.setpoint_y2_2.setObjectName("setpoint_y2_2")
        self.gridlayout8.addWidget(self.setpoint_y2_2, 16, 8, 1, 1)
        self.label_160 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_160.setObjectName("label_160")
        self.gridlayout8.addWidget(self.label_160, 17, 0, 1, 2)
        self.forwardbox_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.forwardbox_2.setObjectName("forwardbox_2")
        self.gridlayout8.addWidget(self.forwardbox_2, 17, 2, 1, 4)
        self.label_163 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_163.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_163.setFont(font)
        self.label_163.setObjectName("label_163")
        self.gridlayout8.addWidget(self.label_163, 17, 6, 1, 1)
        self.forward_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.forward_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.forward_y1_2.setObjectName("forward_y1_2")
        self.gridlayout8.addWidget(self.forward_y1_2, 17, 7, 1, 1)
        self.forward_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.forward_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.forward_y2_2.setObjectName("forward_y2_2")
        self.gridlayout8.addWidget(self.forward_y2_2, 17, 8, 1, 1)
        self.label_157 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_157.setObjectName("label_157")
        self.gridlayout8.addWidget(self.label_157, 18, 0, 1, 2)
        self.reflectedbox_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.reflectedbox_2.setObjectName("reflectedbox_2")
        self.gridlayout8.addWidget(self.reflectedbox_2, 18, 2, 1, 4)
        self.label_161 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_161.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_161.setFont(font)
        self.label_161.setObjectName("label_161")
        self.gridlayout8.addWidget(self.label_161, 18, 6, 1, 1)
        self.reflected_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.reflected_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.reflected_y1_2.setObjectName("reflected_y1_2")
        self.gridlayout8.addWidget(self.reflected_y1_2, 18, 7, 1, 1)
        self.reflected_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.reflected_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.reflected_y2_2.setObjectName("reflected_y2_2")
        self.gridlayout8.addWidget(self.reflected_y2_2, 18, 8, 1, 1)
        self.label_159 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_159.setObjectName("label_159")
        self.gridlayout8.addWidget(self.label_159, 19, 0, 1, 2)
        self.loadbox_2 = widget.TauValueLabel(self.tauGroupBox_8)
        self.loadbox_2.setObjectName("loadbox_2")
        self.gridlayout8.addWidget(self.loadbox_2, 19, 2, 1, 4)
        self.label_162 = QtGui.QLabel(self.tauGroupBox_8)
        self.label_162.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_162.setFont(font)
        self.label_162.setObjectName("label_162")
        self.gridlayout8.addWidget(self.label_162, 19, 6, 1, 1)
        self.load_y1_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.load_y1_2.setMaximumSize(QtCore.QSize(16, 16))
        self.load_y1_2.setObjectName("load_y1_2")
        self.gridlayout8.addWidget(self.load_y1_2, 19, 7, 1, 1)
        self.load_y2_2 = QtGui.QCheckBox(self.tauGroupBox_8)
        self.load_y2_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.load_y2_2.setObjectName("load_y2_2")
        self.gridlayout8.addWidget(self.load_y2_2, 19, 8, 1, 1)
        self.startbutton5 = widget.TauCommandButton(self.tauGroupBox_8)
        self.startbutton5.setObjectName("startbutton5")
        self.gridlayout8.addWidget(self.startbutton5, 20, 0, 1, 5)
        self.stopbutton5 = widget.TauCommandButton(self.tauGroupBox_8)
        self.stopbutton5.setEnabled(False)
        self.stopbutton5.setObjectName("stopbutton5")
        self.gridlayout8.addWidget(self.stopbutton5, 20, 5, 1, 1)
        self.saveasbutton5 = widget.TauCommandButton(self.tauGroupBox_8)
        self.saveasbutton5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.saveasbutton5.setObjectName("saveasbutton5")
        self.gridlayout8.addWidget(self.saveasbutton5, 20, 6, 1, 4)
        self.file5 = QtGui.QLabel(self.tauGroupBox_8)
        self.file5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.file5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.file5.setObjectName("file5")
        self.gridlayout8.addWidget(self.file5, 21, 0, 1, 10)
        self.gridlayout7.addWidget(self.tauGroupBox_8, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_13, "")
        self.hboxlayout.addWidget(self.tabWidget)
        self.Counter = QtGui.QLabel(self.centralwidget)
        self.Counter.setGeometry(QtCore.QRect(19,797,1,1))
        self.Counter.setMaximumSize(QtCore.QSize(1,1))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DATA LOGGER", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Y1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Y2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Av Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.avratebox.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/AverageRate", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "A/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Av Thick", None, QtGui.QApplication.UnicodeUTF8))
        self.avthicknessbox.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/AverageThickness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "kA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Rate 1", None, QtGui.QApplication.UnicodeUTF8))
        self.rate1box.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/Rate1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "A/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Rate 2", None, QtGui.QApplication.UnicodeUTF8))
        self.rate2box.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/Rate2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "A/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Thick 1", None, QtGui.QApplication.UnicodeUTF8))
        self.thickness1box.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/Thickness1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "kA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Thick 2", None, QtGui.QApplication.UnicodeUTF8))
        self.thickness2box.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/Thickness2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "kA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Freq 1", None, QtGui.QApplication.UnicodeUTF8))
        self.frequency1box.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/Frequency1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Freq 2", None, QtGui.QApplication.UnicodeUTF8))
        self.frequency2box.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/Frequency2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.startbutton1.setText(QtGui.QApplication.translate("MainWindow", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.stopbutton1.setText(QtGui.QApplication.translate("MainWindow", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.saveasbutton1.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.file1.setText(QtGui.QApplication.translate("MainWindow", "log.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Rate Thickness Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_96.setText(QtGui.QApplication.translate("MainWindow", "Y1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_97.setText(QtGui.QApplication.translate("MainWindow", "Y2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_98.setText(QtGui.QApplication.translate("MainWindow", "Penning1", None, QtGui.QApplication.UnicodeUTF8))
        self.pirani1box.setModel(QtGui.QApplication.translate("MainWindow", "lab/15/vgct-01/P1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_99.setText(QtGui.QApplication.translate("MainWindow", "mbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_100.setText(QtGui.QApplication.translate("MainWindow", "Penning2", None, QtGui.QApplication.UnicodeUTF8))
        self.pirani2box.setModel(QtGui.QApplication.translate("MainWindow", "lab/15/vgct-01/P2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_101.setText(QtGui.QApplication.translate("MainWindow", "mbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_102.setText(QtGui.QApplication.translate("MainWindow", "Pirani1", None, QtGui.QApplication.UnicodeUTF8))
        self.penning1box.setModel(QtGui.QApplication.translate("MainWindow", "lab/15/vgct-01/P4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_103.setText(QtGui.QApplication.translate("MainWindow", "mbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_104.setText(QtGui.QApplication.translate("MainWindow", "Pirani2", None, QtGui.QApplication.UnicodeUTF8))
        self.penning2box.setModel(QtGui.QApplication.translate("MainWindow", "lab/15/vgct-01/P5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_105.setText(QtGui.QApplication.translate("MainWindow", "mbar", None, QtGui.QApplication.UnicodeUTF8))
        self.startbutton2.setText(QtGui.QApplication.translate("MainWindow", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.stopbutton2.setText(QtGui.QApplication.translate("MainWindow", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.saveasbutton2.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.file2.setText(QtGui.QApplication.translate("MainWindow", "log.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "MKS Gauge controller", None, QtGui.QApplication.UnicodeUTF8))
        self.label_115.setText(QtGui.QApplication.translate("MainWindow", "Y1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_116.setText(QtGui.QApplication.translate("MainWindow", "Y2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_117.setText(QtGui.QApplication.translate("MainWindow", "Capacitor1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_118.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_119.setText(QtGui.QApplication.translate("MainWindow", "Capacitor2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_120.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_121.setText(QtGui.QApplication.translate("MainWindow", "DC bias", None, QtGui.QApplication.UnicodeUTF8))
        self.label_122.setText(QtGui.QApplication.translate("MainWindow", "Volt", None, QtGui.QApplication.UnicodeUTF8))
        self.startbutton3.setText(QtGui.QApplication.translate("MainWindow", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.stopbutton3.setText(QtGui.QApplication.translate("MainWindow", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.saveasbutton3.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.file3.setText(QtGui.QApplication.translate("MainWindow", "log.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "MKS MWH-5 and RFC-5MW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_134.setText(QtGui.QApplication.translate("MainWindow", "Y1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_135.setText(QtGui.QApplication.translate("MainWindow", "Y2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_136.setText(QtGui.QApplication.translate("MainWindow", "Setpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_137.setText(QtGui.QApplication.translate("MainWindow", "Watts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_138.setText(QtGui.QApplication.translate("MainWindow", "Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.label_139.setText(QtGui.QApplication.translate("MainWindow", "Watts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_140.setText(QtGui.QApplication.translate("MainWindow", "Reflected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_141.setText(QtGui.QApplication.translate("MainWindow", "Watts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_142.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_143.setText(QtGui.QApplication.translate("MainWindow", "Watts", None, QtGui.QApplication.UnicodeUTF8))
        self.startbutton4.setText(QtGui.QApplication.translate("MainWindow", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.stopbutton4.setText(QtGui.QApplication.translate("MainWindow", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.saveasbutton4.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.file4.setText(QtGui.QApplication.translate("MainWindow", "log.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Plasma Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_106.setText(QtGui.QApplication.translate("MainWindow", "Y1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_107.setText(QtGui.QApplication.translate("MainWindow", "Y2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Av Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.avratebox_2.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/AverageRate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_108.setText(QtGui.QApplication.translate("MainWindow", "A/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_109.setText(QtGui.QApplication.translate("MainWindow", "Av Thick", None, QtGui.QApplication.UnicodeUTF8))
        self.avthicknessbox_2.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/AverageThickness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_110.setText(QtGui.QApplication.translate("MainWindow", "kA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_111.setText(QtGui.QApplication.translate("MainWindow", "Rate 1", None, QtGui.QApplication.UnicodeUTF8))
        self.rate1box_2.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/Rate1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_112.setText(QtGui.QApplication.translate("MainWindow", "A/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_113.setText(QtGui.QApplication.translate("MainWindow", "Rate 2", None, QtGui.QApplication.UnicodeUTF8))
        self.rate2box_2.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/Rate2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_114.setText(QtGui.QApplication.translate("MainWindow", "A/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_123.setText(QtGui.QApplication.translate("MainWindow", "Thick 1", None, QtGui.QApplication.UnicodeUTF8))
        self.thickness1box_2.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/Thickness1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_124.setText(QtGui.QApplication.translate("MainWindow", "kA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_125.setText(QtGui.QApplication.translate("MainWindow", "Thick 2", None, QtGui.QApplication.UnicodeUTF8))
        self.thickness2box_2.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/Thickness2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_126.setText(QtGui.QApplication.translate("MainWindow", "kA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_127.setText(QtGui.QApplication.translate("MainWindow", "Freq 1", None, QtGui.QApplication.UnicodeUTF8))
        self.frequency1box_2.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/Frequency1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_128.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_129.setText(QtGui.QApplication.translate("MainWindow", "Freq 2", None, QtGui.QApplication.UnicodeUTF8))
        self.frequency2box_2.setModel(QtGui.QApplication.translate("MainWindow", "lab15/vc/ratethickness/Frequency2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_130.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_131.setText(QtGui.QApplication.translate("MainWindow", "Penning1", None, QtGui.QApplication.UnicodeUTF8))
        self.pirani1box_2.setModel(QtGui.QApplication.translate("MainWindow", "lab/15/vgct-01/P1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_146.setText(QtGui.QApplication.translate("MainWindow", "mbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_147.setText(QtGui.QApplication.translate("MainWindow", "Penning2", None, QtGui.QApplication.UnicodeUTF8))
        self.pirani2box_2.setModel(QtGui.QApplication.translate("MainWindow", "lab/15/vgct-01/P2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_149.setText(QtGui.QApplication.translate("MainWindow", "mbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_148.setText(QtGui.QApplication.translate("MainWindow", "Pirani1", None, QtGui.QApplication.UnicodeUTF8))
        self.penning1box_2.setModel(QtGui.QApplication.translate("MainWindow", "lab/15/vgct-01/P4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_145.setText(QtGui.QApplication.translate("MainWindow", "mbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_132.setText(QtGui.QApplication.translate("MainWindow", "Pirani2", None, QtGui.QApplication.UnicodeUTF8))
        self.penning2box_2.setModel(QtGui.QApplication.translate("MainWindow", "lab/15/vgct-01/P5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_144.setText(QtGui.QApplication.translate("MainWindow", "mbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_150.setText(QtGui.QApplication.translate("MainWindow", "Capacitor1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_151.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_153.setText(QtGui.QApplication.translate("MainWindow", "Capacitor2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_155.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_156.setText(QtGui.QApplication.translate("MainWindow", "DC bias", None, QtGui.QApplication.UnicodeUTF8))
        self.label_154.setText(QtGui.QApplication.translate("MainWindow", "Volt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_158.setText(QtGui.QApplication.translate("MainWindow", "Setpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_164.setText(QtGui.QApplication.translate("MainWindow", "Watts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_160.setText(QtGui.QApplication.translate("MainWindow", "Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.label_163.setText(QtGui.QApplication.translate("MainWindow", "Watts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_157.setText(QtGui.QApplication.translate("MainWindow", "Reflected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_161.setText(QtGui.QApplication.translate("MainWindow", "Watts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_159.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_162.setText(QtGui.QApplication.translate("MainWindow", "Watts", None, QtGui.QApplication.UnicodeUTF8))
        self.startbutton5.setText(QtGui.QApplication.translate("MainWindow", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.stopbutton5.setText(QtGui.QApplication.translate("MainWindow", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.saveasbutton5.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.file5.setText(QtGui.QApplication.translate("MainWindow", "log.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), QtGui.QApplication.translate("MainWindow", "Common", None, QtGui.QApplication.UnicodeUTF8))

from tau import widget
from tau.widget import qwt

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

